version: '3.8'

services:
  nats-server:
    image: nats:latest
  
  client-gateway:
    build:
      context: ./clientGW-ms-example
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
 
  auth-ms:
    build:
      context: ./auth-ms-example
      dockerfile: dockerfile.prod    
    image: auth-ms-prod
    ports:
      - ${AUTH_MS_PORT}:${AUTH_MS_PORT}  
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms-example 
      dockerfile: dockerfile.prod    
    image: products-ms-prod
    ports:
      - ${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}  
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db 

  payments-ms:
    build:
      context: ./payments-ms-example
      dockerfile: dockerfile.prod    
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}   
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
 
  orders-ms:
    build: 
      context: ./orders-ms-example 
      dockerfile: dockerfile.prod 
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}         
    image: orders-ms-prod 
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}
 