apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-427201/image-registry/client-gateway
        name: client-gateway
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats:4222"  
        resources: {}
status: {}
